export const ADD_VISITED_VIEW = 'ADD_VISITED_VIEW';
export const DEL_VISITED_VIEW = 'DEL_VISITED_VIEW';
export const DEL_ALL_VISITED_VIEW = 'DEL_ALL_VISITED_VIEW';
export const DEL_OTHER_VISITED_VIEW = 'DEL_OTHER_VISITED_VIEW';
